///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AssetsConfig {
  AssetsConfig._();

  static const String iconsAttachment = 'assets/icons/attachment.png';
  static const String iconsAttachmentExcel =
      'assets/icons/attachment_excel.png';
  static const String iconsAttachmentPdf = 'assets/icons/attachment_pdf.png';
  static const String iconsAttachmentPicture =
      'assets/icons/attachment_picture.png';
  static const String iconsAttachmentPpt = 'assets/icons/attachment_ppt.png';
  static const String iconsAttachmentTxt = 'assets/icons/attachment_txt.png';
  static const String iconsAttachmentWord = 'assets/icons/attachment_word.png';
  static const String iconsCode = 'assets/icons/code.png';
  static const String iconsFilter = 'assets/icons/filter.png';
  static const String iconsFilterOn = 'assets/icons/filter_on.png';
  static const String iconsLock = 'assets/icons/lock.png';
  static const String iconsMore = 'assets/icons/more.png';
  static const String iconsOperationAgree = 'assets/icons/operation_agree.png';
  static const String iconsOperationAssign =
      'assets/icons/operation_assign.png';
  static const String iconsOperationBatch = 'assets/icons/operation_batch.png';
  static const String iconsOperationClose = 'assets/icons/operation_close.png';
  static const String iconsOperationDelete =
      'assets/icons/operation_delete.png';
  static const String iconsOperationRecall =
      'assets/icons/operation_recall.png';
  static const String iconsOperationReturn =
      'assets/icons/operation_return.png';
  static const String iconsOperationSubmit =
      'assets/icons/operation_submit.png';
  static const String iconsOperationSupplement =
      'assets/icons/operation_supplement.png';
  static const String iconsOperationSupply =
      'assets/icons/operation_supply.png';
  static const String iconsPlanDay = 'assets/icons/plan_day.png';
  static const String iconsPlanMonth = 'assets/icons/plan_month.png';
  static const String iconsPlanWeek = 'assets/icons/plan_week.png';
  static const String iconsUser = 'assets/icons/user.png';
  static const String imagesAppIcon = 'assets/images/app_icon.png';
  static const String imagesAppLogo = 'assets/images/app_logo.png';
  static const String imagesAppSlogan = 'assets/images/app_slogan.png';
  static const String imagesAppSplash = 'assets/images/app_splash.png';
  static const String imagesAvatar = 'assets/images/avatar.png';
  static const String imagesEmptyCaptcha = 'assets/images/empty_captcha.jpg';
  static const String imagesHomeBanner = 'assets/images/home_banner.png';
  static const String imagesLoginBackground =
      'assets/images/login_background.png';
  static const String imagesNoData = 'assets/images/no_data.png';
  static const String imagesSystemData = 'assets/images/system_data.png';
  static const String imagesSystemDataOn = 'assets/images/system_data_on.png';
  static const String imagesSystemDzdxj = 'assets/images/system_dzdxj.png';
  static const String imagesSystemDzdxjOn = 'assets/images/system_dzdxj_on.png';
  static const String imagesSystemLjyyx = 'assets/images/system_ljyyx.png';
  static const String imagesSystemLjyyxOn = 'assets/images/system_ljyyx_on.png';
  static const String imagesSystemProgramme =
      'assets/images/system_programme.png';
  static const String imagesSystemProgrammeOn =
      'assets/images/system_programme_on.png';
  static const String imagesSystemTcx = 'assets/images/system_tcx.png';
  static const String imagesSystemTcxOn = 'assets/images/system_tcx_on.png';
  static const String imagesSystemUser = 'assets/images/system_user.png';
  static const String imagesSystemUserOn = 'assets/images/system_user_on.png';
  static const String imagesSystemYyx = 'assets/images/system_yyx.png';
  static const String imagesSystemYyxOn = 'assets/images/system_yyx_on.png';
  static const String tabIconsExamine = 'assets/tab_icons/examine.png';
  static const String tabIconsExamineActive =
      'assets/tab_icons/examine_active.png';
  static const String tabIconsMessage = 'assets/tab_icons/message.png';
  static const String tabIconsMessageActive =
      'assets/tab_icons/message_active.png';
  static const String tabIconsMine = 'assets/tab_icons/mine.png';
  static const String tabIconsMineActive = 'assets/tab_icons/mine_active.png';
  static const String tabIconsPlatform = 'assets/tab_icons/platform.png';
  static const String tabIconsPlatformActive =
      'assets/tab_icons/platform_active.png';
  static const String tabIconsQuery = 'assets/tab_icons/query.png';
  static const String tabIconsQueryActive = 'assets/tab_icons/query_active.png';
  static const String tabIconsSupervise = 'assets/tab_icons/supervise.png';
  static const String tabIconsSuperviseActive =
      'assets/tab_icons/supervise_active.png';
}
